# Google Sheet 嵌入網址（教師可修改，留空則顯示提示）
# 將 Google Sheet 發布到網路後，取得 iframe src 貼在這裡
GOOGLE_SHEET_EMBED_URL = "https://docs.google.com/spreadsheets/d/e/2PACX-1vTxHg5AWk4_6ORofibRqA8tsvedMyGLbHQmjZsXCBbd3eP3EQ1EIeK8OfVt8341zZxg/pubhtml?widget=true&headers=false"

WEEKS = {
    1: {
        "title": "問題體驗",
        "theme": "你今天等了多久？",
        "objectives": "理解驗車場的運作流程與痛點，建立對專題的興趣",
        "checklist": [
            "觀看教師展示系統操作",
            "親自用手機操作預約與中控台",
            "參與小組討論，寫出 3 個驗車場痛點",
            "上台分享小組觀察結果",
            "回家觀察一個排隊場景，畫出流程圖",
        ],
        "keywords": ["使用者體驗", "痛點分析", "流程圖", "觀察力"],
        "activities": [
            "教師用投影機展示系統：手機預約 → 中控台即時更新 → 點完成 → 統計改變",
            "各組輪流操作：一組預約、一組看中控台、一組觀察資料變化",
            "小組討論：車主最困擾什麼？櫃台人員最困擾什麼？",
            "各組寫出 3 個痛點並上台分享",
            "教師總結本學期目標",
        ],
        "ai_prompts": [],
        "reflection": "你今天觀察到最讓你印象深刻的排隊場景是什麼？為什麼？",
    },
    2: {
        "title": "需求訪談 + 功能排序",
        "theme": "使用者在想什麼？",
        "objectives": "學會使用者訪談技巧，並能將需求排序優先順序",
        "checklist": [
            "學會 5W1H 訪談法（誰、什麼、何時、哪裡、為什麼、怎麼做）",
            "參與角色扮演（車主/櫃台/檢驗員）",
            "完成痛點牆和需求牆",
            "學會 MoSCoW 法（Must/Should/Could/Won't）",
            "各組排出功能優先序清單",
        ],
        "keywords": ["5W1H", "使用者訪談", "MoSCoW", "需求排序", "優先順序"],
        "activities": [
            "教師教 5W1H 訪談法，附填空式訪談模板",
            "角色扮演：三人一組（車主/櫃台/記錄員），模擬驗車場對話",
            "用便利貼貼出痛點牆 + 需求牆",
            "教師教 MoSCoW 法，各組排出功能優先序",
            "各組分享功能清單，組間互補",
        ],
        "ai_prompts": [],
        "reflection": "你覺得驗車場最迫切需要解決的問題是什麼？為什麼？",
    },
    3: {
        "title": "紙本原型",
        "theme": "畫出來試試",
        "objectives": "用手繪快速驗證介面想法，不寫程式也能設計系統",
        "checklist": [
            "拿到手機框模板和 UI 元件貼紙",
            "各組分工畫出 1 個頁面（車主首頁/預約表單/中控台/成功頁）",
            "完成便利貼走查（一人操作、一人模擬點擊）",
            "根據走查回饋修改紙本原型",
            "拍照繳交紙本原型照片",
        ],
        "keywords": ["紙本原型", "手機框模板", "便利貼走查", "UI 元件"],
        "activities": [
            "教師展示好的和不好的介面對比",
            "發放材料：手機框模板 + UI 元件貼紙（按鈕、輸入框、狀態標籤）",
            "各組分工，每組只做 1 個頁面",
            "便利貼走查：一人拿紙本操作，另一人手指模擬點擊",
            "根據走查回饋修改，拍照繳交",
        ],
        "ai_prompts": [],
        "reflection": "畫完原型後，你發現原本想的跟實際畫出來有什麼不一樣？",
    },
    4: {
        "title": "Figma 數位化",
        "theme": "讓它變好看",
        "objectives": "將紙本原型轉為數位線框圖，學會基本 UI 設計原則",
        "checklist": [
            "打開教師提供的 Figma 模板",
            "將上週紙本原型轉為 Figma 數位版",
            "修改顏色、文字、位置",
            "參與跨組互評",
            "完成高保真原型",
        ],
        "keywords": ["Figma", "線框圖", "配色", "排版", "高保真原型"],
        "activities": [
            "教師展示 Figma 模板（已有頁面框架，只需改顏色文字）",
            "學生將紙本原型轉為數位版",
            "跨組互評：哪個配色最清楚？哪個按鈕位置最好按？",
            "教師給各組回饋",
        ],
        "ai_prompts": [],
        "reflection": "數位版跟紙本比起來，你做了哪些改變？為什麼？",
    },
    5: {
        "title": "opencode + HTML 入門",
        "theme": "跟 AI 說：幫我寫個網頁",
        "objectives": "學會使用 opencode 生成 HTML，理解網頁骨架結構",
        "checklist": [
            "註冊 OpenRouter 並取得 API Key",
            "安裝 opencode",
            "學會提示語三要素（誰要用 + 要做什麼 + 長什麼樣）",
            "用 opencode 生成車主首頁 HTML",
            "修改至少 3 處文字（標題、按鈕、頁尾）",
        ],
        "keywords": ["opencode", "DeepSeek", "OpenRouter", "HTML", "提示語"],
        "activities": [
            "註冊 OpenRouter → 取得 API Key → 安裝 opencode",
            "教提示語三要素：誰要用 + 要做什麼 + 長什麼樣",
            "opencode 生成車主首頁 HTML",
            "學生修改標題文字、按鈕文字、頁尾文字",
            "教師總結：HTML = 骨架",
        ],
        "ai_prompts": [
            "幫我建立一個驗車場車主首頁的 HTML 檔案，包含：大標題「今天來驗車，先看即時流量」、一個橘色「我要線上預約」按鈕、6 個時段狀態卡片（09:00、10:00、11:00、13:30、14:30、15:30）、每個卡片有時段名稱、容量條、狀態標籤、頁尾有 4 步驟流程說明，手機和電腦都能看",
        ],
        "reflection": "第一次讓 AI 幫你寫程式，你的感覺是什麼？",
    },
    6: {
        "title": "CSS 美化",
        "theme": "穿上衣服",
        "objectives": "學會用 CSS 讓網頁變好看，理解樣式與內容分離的概念",
        "checklist": [
            "用 opencode 為車主首頁加上 CSS",
            "設定主色 Teal 和強調色橘色",
            "加入卡片圓角、陰影、間距",
            "調整字型與顏色",
            "讓頁面看起來跟 Figma 設計稿相近",
        ],
        "keywords": ["CSS", "樣式", "配色", "響應式設計", "Flexbox"],
        "activities": [
            "展示同樣 HTML 加上 CSS 前後的差異",
            "教 CSS 提示語怎麼寫",
            "opencode 加入 CSS 樣式",
            "學生修改顏色數字、調間距",
            "對照 Figma 設計稿調整",
        ],
        "ai_prompts": [
            "幫我的驗車場車主首頁加上 CSS：主色用 Teal #1f6f78、強調色用橘色 #d66a31、卡片有圓角 8px 和陰影、字型用微軟正黑體、手機上時段卡片改為垂直排列、狀態標籤用不同顏色（空閒=綠色、普通=Teal、忙碌=黃色、滿載=紅色）",
        ],
        "reflection": "你覺得 CSS 最難的是什麼？最容易的是什麼？",
    },
    7: {
        "title": "JavaScript 互動",
        "theme": "按下去會怎樣？",
        "objectives": "學會用 JavaScript 為網頁加入互動效果",
        "checklist": [
            "用 opencode 加入按鈕點擊事件",
            "加入時段選擇互動效果",
            "加入表單驗證（檢查車牌格式）",
            "測試所有互動功能正常",
            "修改一個 JS 行為（改訊息文字、改顏色）",
        ],
        "keywords": ["JavaScript", "事件", "互動設計", "表單驗證", "DOM"],
        "activities": [
            "展示 JS 效果：點按鈕跳出畫面、選擇時段顏色變化",
            "教 JS 提示語怎麼寫",
            "opencode 加入點擊事件",
            "加入時段選擇和表單驗證",
            "各組互測互動功能",
        ],
        "ai_prompts": [
            "幫我的驗車場車主首頁加入 JavaScript：點「我要線上預約」按鈕時彈出確認視窗問「是否前往預約頁面？」、選擇日期後自動更新時段狀態顯示、車牌輸入框檢查格式（英文-數字）",
        ],
        "reflection": "你覺得互動功能中，哪一個最有用？為什麼？",
    },
    8: {
        "title": "前端整合",
        "theme": "把三寶合體",
        "objectives": "將 HTML/CSS/JS 整合成完整的車主端系統",
        "checklist": [
            "用 opencode 將車主頁、預約頁、成功頁合併",
            "確認頁面之間可以切換",
            "確認預約表單有所有必要欄位",
            "確認成功頁顯示預約資訊",
            "用手機測試頁面顯示正常",
        ],
        "keywords": ["前端整合", "多頁面", "使用者流程", "響應式"],
        "activities": [
            "展示最終目標：三個頁面可以互相切換",
            "opencode 將所有頁面整合在一起",
            "各組完善缺少的元素",
            "各組展示目前完成度",
        ],
        "ai_prompts": [
            "幫我把車主首頁、預約表單、預約成功頁整合成一個完整的 Flask 專案：車主首頁（/）有即時流量和預約按鈕、預約頁（/reserve）有車牌、姓名、手機、日期、時段欄位、成功頁（/success）顯示預約編號和車牌，使用 Jinja2 模板共用 header/footer",
        ],
        "reflection": "從紙本原型到真的網頁，你覺得最難克服的是什麼？",
    },
    9: {
        "title": "Python 基礎",
        "theme": "電腦幫你算",
        "objectives": "理解 Python 的基本邏輯，能透過 AI 生成並修改程式",
        "checklist": [
            "用 opencode 生成檢驗週期計算器",
            "修改週期規則數字（5年、10年）",
            "用 opencode 生成時段可用判斷程式",
            "測試計算結果是否正確",
            "理解函式的概念（輸入→處理→輸出）",
        ],
        "keywords": ["Python", "函式", "條件判斷", "輸入輸出", "計算邏輯"],
        "activities": [
            "用生活例子說明 Python 能做什麼",
            "opencode 提示語：檢驗週期計算器",
            "學生修改週期規則的門檻數字",
            "第二個練習：時段可用判斷",
            "總結：函式 = 輸入 → 處理 → 輸出",
        ],
        "ai_prompts": [
            "用 Python 寫一個「車輛檢驗週期計算器」：輸入出廠年份、車種，輸出下次檢驗日期和檢驗頻率。規則：自用小客車未滿5年免檢、5-10年每年一次、10年以上每年二次、自用小貨車全部每年一次。",
        ],
        "reflection": "你覺得讓 AI 寫程式跟自己從零開始寫，最大的差別是什麼？",
    },
    10: {
        "title": "Flask 入門",
        "theme": "變成網站",
        "objectives": "理解 Flask 如何讓 Python 程式變成網頁",
        "checklist": [
            "用 opencode 建立 Flask 應用程式",
            "將 W8 的 HTML 放進 Flask 模板中",
            "設定至少 3 個路由（/、/reserve、/success）",
            "測試不同網址對應不同頁面",
            "理解「路由 = 網址對應頁面」的概念",
        ],
        "keywords": ["Flask", "路由", "網頁伺服器", "模板", "localhost"],
        "activities": [
            "比喻：Flask 是廚房，把 Python 料理變成網頁端上桌",
            "opencode 建立第一個 Flask 應用",
            "把上週的 HTML 放進 templates/ 資料夾",
            "測試路由：不同的網址對應不同的頁面",
            "總結",
        ],
        "ai_prompts": [
            "建立一個 Flask 網頁應用：首頁（/）顯示車主首頁、預約頁（/reserve）顯示預約表單、成功頁（/success）顯示「預約成功」、使用 Jinja2 模板共用 navigation bar、HTML 放在 templates/ 資料夾",
        ],
        "reflection": "Flask 在你心目中是做什麼用的？用你自己的話說明。",
    },
    11: {
        "title": "API 設計與串接",
        "theme": "前端點餐、後端做菜",
        "objectives": "理解 API 的概念，能建立並測試基本的 API",
        "checklist": [
            "用 opencode 建立 GET API（/api/slots）",
            "用 opencode 建立 POST API（/api/reservations）",
            "用瀏覽器測試 GET API 回傳結果",
            "用 opencode 測試 POST API",
            "理解 API 是前端和後端溝通的方式",
        ],
        "keywords": ["API", "GET", "POST", "JSON", "請求和回應"],
        "activities": [
            "餐廳點餐比喻：你點餐（請求）→廚房做→端出來（回應）",
            "opencode 建立 GET /api/slots",
            "opencode 建立 POST /api/reservations",
            "用瀏覽器測試 API",
            "總結 API 角色",
        ],
        "ai_prompts": [
            "幫我的 Flask 加入 API：GET /api/slots 接收日期參數，回傳當天各時段預約狀況（時段名稱、已預約數、最大容量、狀態百分比）、POST /api/reservations 接收 JSON 格式的預約資料（車牌、姓名、手機、日期、時段），新增後回傳預約編號",
        ],
        "reflection": "用你自己的話解釋 API 是什麼，可以舉生活中的例子。",
    },
    12: {
        "title": "前後端整合",
        "theme": "打通了！",
        "objectives": "將前端表單串接到後端 API，完成完整資料流",
        "checklist": [
            "將預約表單串接到 /api/reservations",
            "完成「填寫 → 送出 → 資料進資料庫」流程",
            "車主首頁從 API 讀取即時資料",
            "測試完整流程：手機預約 → 首頁即時更新",
            "記錄遇到的問題",
        ],
        "keywords": ["前後端串接", "資料流", "表單提交", "API 呼叫", "非同步"],
        "activities": [
            "展示目標：填寫預約→送出→資料進資料庫→首頁數字改變",
            "opencode 將預約表單串接到 API",
            "車主首頁從 API 讀取即時資料",
            "測試完整流程",
            "各組記錄卡住的地方",
        ],
        "ai_prompts": [
            "幫我修改預約表單的前端 JavaScript：使用 fetch() 將表單資料 POST 到 /api/reservations、送出後顯示載入中狀態、成功後跳轉到成功頁、失敗時顯示錯誤訊息、車主首頁使用 fetch() 從 /api/slots 讀取即時資料並顯示",
        ],
        "reflection": "從填寫預約到資料存進資料庫，這中間發生了什麼事？",
    },
    13: {
        "title": "SQLite 認識",
        "theme": "資料庫長這樣",
        "objectives": "認識 SQLite 資料庫，能用 DB Browser 瀏覽資料",
        "checklist": [
            "安裝 DB Browser for SQLite",
            "打開系統的 inspection.db",
            "瀏覽 vehicles 資料表內容",
            "瀏覽 reservations 資料表內容",
            "瀏覽 time_slots 資料表內容",
        ],
        "keywords": ["SQLite", "資料庫", "DB Browser", "資料表", "欄位"],
        "activities": [
            "Excel 比喻：活頁簿=資料庫、工作表=資料表、欄=欄位、列=記錄",
            "安裝 DB Browser",
            "打開 inspection.db，看看裡面有什麼資料表",
            "用「瀏覽資料」功能看每張表的內容",
            "對照系統功能，找出資料對應的程式碼",
        ],
        "ai_prompts": [],
        "reflection": "資料庫跟 Excel 有什麼像和不像的地方？",
    },
    14: {
        "title": "SQL 基本操作",
        "theme": "新增、查詢、修改、刪除",
        "objectives": "學會 SQL 基本語法，能執行查詢和新增資料",
        "checklist": [
            "學會 SELECT 語法（查詢資料）",
            "學會 INSERT 語法（新增資料）",
            "學會 DELETE 語法（刪除資料）",
            "在 DB Browser 中執行 5 次 SQL 指令",
            "用 opencode 幫忙寫不熟的 SQL",
        ],
        "keywords": ["SQL", "SELECT", "INSERT", "DELETE", "WHERE"],
        "activities": [
            "教 3 個基本 SQL：SELECT、INSERT、DELETE",
            "學生在 DB Browser 執行：查詢所有車輛、查詢今天預約、新增一筆預約、刪除測試資料",
            "opencode 幫忙寫 SQL：「幫我寫 SQL 查詢今天所有已報到的預約」",
            "學生修改 WHERE 條件觀察結果變化",
        ],
        "ai_prompts": [
            "幫我寫 SQL 語法：查詢 vehicles 資料表中所有車種為「自用小客車」的車輛、查詢 reservations 資料表中今天所有狀態為「檢驗中」的預約、新增一筆車輛資料（車牌=TEST-9999, 車主=測試, 手機=0911111111）",
        ],
        "reflection": "用指令操作資料跟你平常操作 Excel 有什麼不一樣的感覺？",
    },
    15: {
        "title": "資料關聯概念",
        "theme": "一輛車可以預約很多次",
        "objectives": "理解資料表之間的關聯（一對多關係）",
        "checklist": [
            "理解「一個車牌對多筆預約」的一對多關係",
            "用 DB Browser 查看 vehicles 和 reservations 的關聯",
            "用 opencode 協助寫 JOIN 查詢",
            "理解為什麼要把車輛和預約分開放",
            "完成 JOIN 查詢測試",
        ],
        "keywords": ["一對多", "關聯", "JOIN", "主鍵", "外鍵"],
        "activities": [
            "展示一對多關係：用 Excel 展示一個車牌對多筆預約",
            "DB Browser 查看關聯欄位",
            "opencode 寫 JOIN 查詢",
            "討論為什麼要分表",
        ],
        "ai_prompts": [
            "幫我寫 SQL JOIN 查詢：查詢每筆預約（reservations）對應的車輛資料（vehicles），顯示車牌、車主姓名、手機、預約日期、時段、狀態，用 LEFT JOIN",
        ],
        "reflection": "為什麼不直接把車輛資料和預約資料放在同一個表格？分開放的好處是什麼？",
    },
    16: {
        "title": "資料庫應用實戰",
        "theme": "資料庫畢業了",
        "objectives": "將 SQLite 查詢整合進 Flask，完成資料驅動的系統",
        "checklist": [
            "用 opencode 將 SQL 查詢寫進 Flask 路由",
            "確認新增一筆資料後重新整理還在",
            "確認關機重開後資料還在",
            "測試所有資料相關功能",
            "完成資料庫整合驗收",
        ],
        "keywords": ["Flask+SQLite", "資料持久化", "整合應用", "驗收"],
        "activities": [
            "展示目標：Flask 從資料庫讀取資料→前端顯示",
            "opencode 將 SQL 查詢寫進 Flask",
            "測試：新增資料→重整→還在，關機重開→還在",
            "各組確認資料庫正確串接",
        ],
        "ai_prompts": [
            "幫我把 SQLite 查詢整合進 Flask：首頁從資料庫讀取今日時段狀態、預約頁將表單資料寫入資料庫、中控台從資料庫讀取今日預約列表、所有資料重新整理後不會消失",
        ],
        "reflection": "資料庫讓你的系統有了什麼以前沒有的能力？",
    },
    17: {
        "title": "中控台 + 登入",
        "theme": "不能讓別人看到",
        "objectives": "建立管理員登入機制，保護中控台頁面",
        "checklist": [
            "討論哪些資料是個人資料需要保護",
            "用 opencode 加入管理員登入功能",
            "建立中控台頁面（統計+列表+操作按鈕）",
            "測試：未登入→跳轉登入頁→登入成功→看到中控台",
            "測試：登出後無法再看到中控台",
        ],
        "keywords": ["Session", "登入驗證", "權限管理", "個資保護", "中控台"],
        "activities": [
            "討論為什麼車主不該看到中控台？哪些資料是個資？",
            "opencode 加入登入功能",
            "建立中控台頁面",
            "測試登入流程",
        ],
        "ai_prompts": [
            "幫我的 Flask 加入管理員登入功能：登入頁（/admin/login）有密碼輸入框、密碼為 admin123、登入後用 session 記錄、中控台頁面（/dashboard）需要登入才能看、沒登入自動跳轉到登入頁、有登出功能（/admin/logout）",
        ],
        "reflection": "為什麼需要保護使用者的資料？如果沒有保護可能會發生什麼事？",
    },
    18: {
        "title": "車籍管理 + 個資保護",
        "theme": "車輛資料庫",
        "objectives": "完成車籍管理功能，並實作個資保護機制",
        "checklist": [
            "用 opencode 建立車籍管理頁面",
            "加入車牌搜尋功能",
            "加入新增車輛功能",
            "建立公開查詢 API（只回車種年份、不含個資）",
            "各組互相檢查有無個資外洩",
        ],
        "keywords": ["車籍管理", "搜尋", "CRUD", "個資保護", "API 安全"],
        "activities": [
            "複習哪些資料是個人資料",
            "opencode 建立車籍管理頁面",
            "建立公開查詢 API（保護個資版本）",
            "各組安全檢查：互測能不能看到不該看的資料",
        ],
        "ai_prompts": [
            "幫我的 Flask 加入車籍管理：車籍頁面（/vehicles）需要登入才能看、搜尋框可查車牌/車主/手機、車輛列表顯示所有資料、新增車輛表單、公開 API（/api/public/vehicle-lookup）輸入車牌只回傳車種和年份，不暴露姓名電話",
        ],
        "reflection": "你覺得在系統開發中，個資保護應該在什麼階段開始考慮？",
    },
    19: {
        "title": "除錯 + 部署 + 練習",
        "theme": "找 bug + 上台準備",
        "objectives": "學會基本除錯技巧，將系統部署到區域網路，練習上台展示",
        "checklist": [
            "學會看錯誤訊息（terminal + 瀏覽器主控台）",
            "用 opencode 協助修復至少 2 個 bug",
            "將系統部署到教室電腦",
            "用手機連線測試成功",
            "練習 3 分鐘上台展示",
        ],
        "keywords": ["除錯", "部署", "區域網路", "展示技巧", "錯誤處理"],
        "activities": [
            "教除錯技巧：錯誤訊息複製給 opencode、檢查 terminal",
            "各組自主除錯",
            "部署系統，手機連線測試",
            "各組練習上台（3 分鐘展示 + 2 分鐘問答）",
            "教師給各組建議",
        ],
        "ai_prompts": [
            "我的 Flask 應用出現錯誤（貼上錯誤訊息），請幫我找出問題並修正",
        ],
        "reflection": "準備上台展示的過程中，你覺得自己做得最好的是什麼？",
    },
    20: {
        "title": "成果發表",
        "theme": "我們的系統",
        "objectives": "向全校師生和外聘委員展示專題成果",
        "checklist": [
            "準備好系統展示環境",
            "練習 5 分鐘展示流程",
            "準備 2 分鐘開發心得",
            "準備委員可能問的問題",
            "完成學習歷程記錄繳交",
        ],
        "keywords": ["成果發表", "簡報技巧", "系統展示", "團隊合作"],
        "activities": [
            "每組 5 分鐘系統展示",
            "2 分鐘開發心得分享",
            "3 分鐘委員問答",
            "委員講評 + 頒獎",
            "課程回顧：我最驕傲的是…我最挫折的是…",
        ],
        "ai_prompts": [],
        "reflection": "回顧這 20 週，你最驕傲的是什麼？如果重來一次，你會怎麼做？",
    },
}
